#!/bin/bash

CXX=${CXX:=g++}
OPENCV=`pkg-config --cflags --libs-only-L --libs-only-l opencv`
V4L2=`pkg-config --cflags --libs libv4l2`
echo "Video for Beaglebone Video Applications - derekmolloy.ie"

echo "Building the OpenCV example for the Beaglebone"
${CXX} -O2 ${OPENCV} boneCV.cpp -o boneCV

echo "Building the OpenCV timing example for the Beaglebone"
${CXX} -O2 ${OPENCV} -lrt boneCVtiming.cpp -o boneCVtiming

echo "Building the Video4Linux frame capture program"
${CXX} -O2 -Wall ${V4L2} grabber.c -o grabber

echo "Building the Video4Linux capture example program"
${CXX} -O2 -Wall ${V4L2} capture.c -o capture

echo "Finished"
